# ==== pytest ====
[tool.pytest.ini_options]
minversion = "8.0"
python_files = [
    "tests.py",
    "test_*.py",
]
norecursedirs = ["node_modules", "{{cookiecutter.package_name}}", "my-python-package"]
filterwarnings = "ignore::DeprecationWarning"
